# Generated by Django 3.1.6 on 2023-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230130_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', '1'), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], null=True, verbose_name='Note'),
        ),
    ]
